---
- name: Ensure needed packages are there
  apt:
    name: "{{ docker_install_packages }}"
    state: present
    update_cache: present

- name: Make keyring folder
  file:
    path: /etc/apt/keyrings
    state: present
    mode: '0755'

- name: Add Docker GPG key
  shell: |
    set -euo pipefail
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    chmod a+r /etc/apt/keyrings/docker.gpg

- name: Add Docker Repo (Trixie)
  copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: |
        deb [arch={{ ansible_architecture | default('arm64') }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_lsb.codename | default('trixie') }} stable
  register: docker_repo_file

- name: Update after adding the repo
  apt:
    update_cache: yes
  when: docker_repo_file is changed

- name: Install Docker NGin and CLI and compose plugin optional
  apt:
    name: "{{ ['docker-ce','docker-ce-cli','containered.io','docker-buildx-plugin'] +(['docker-compose-plugin'] if docker_install_compose_plugin else []) }}"
  state: present

- name: Enable and start Docker
  systemd:
    name: docker
    enable: true
    state: started
    
