---
- name: Install prerequisite packages
  apt:
    name: "{{ docker_prerequisites }}"
    state: present
    update_cache: yes
  tags: docker

- name: Create keyrings directory
  file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'
  tags: docker

- name: Download Docker GPG key
  get_url:
    url: "{{ docker_apt_key_url }}"
    dest: /tmp/docker.gpg
    mode: '0644'
  tags: docker

- name: Dearmor and install Docker GPG key
  shell: |
    gpg --dearmor < /tmp/docker.gpg > /usr/share/keyrings/docker.gpg
    chmod 644 /usr/share/keyrings/docker.gpg
  args:
    creates: /usr/share/keyrings/docker.gpg
  tags: docker

- name: Add Docker repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    filename: docker
  tags: docker

- name: Update apt cache after adding repository
  apt:
    update_cache: yes
  tags: docker

- name: Install Docker packages
  apt:
    name: "{{ docker_packages }}"
    state: present
  notify: restart docker
  tags: docker

- name: Ensure Docker service is started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  tags: docker

- name: Add users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ docker_users }}"
  when: docker_users | length > 0
  tags: docker

- name: Verify Docker installation
  command: docker --version
  register: docker_version_output
  changed_when: false
  tags: docker

- name: Verify Docker Compose installation
  command: docker compose version
  register: docker_compose_version_output
  changed_when: false
  tags: docker

- name: Display Docker version
  debug:
    msg: "{{ docker_version_output.stdout }}"
  tags: docker

- name: Display Docker Compose version
  debug:
    msg: "{{ docker_compose_version_output.stdout }}"
  tags: docker

